name: panvimdoc

on:
  push:
    branches: [ main ]
    paths:
      - README.md
      - .github/workflows/docs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v3.0.6
        with:
          vimdoc: auto-fstring.nvim
          description: reminders to keep hydrated while you code
          pandoc: README.md
          toc: false
          version: "NVIM >= v0.8.0"
          demojify: false
          dedupsubheadings: false
          shiftheadinglevelby: -1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_message: 'chore: auto generate docs'
          branch: ${{ github.head_ref }}
          push_options: '--force'
